/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DeterministicDeployer,
  DeterministicDeployerInterface,
} from "../../../../../oz-custom/contracts/internal/DeterministicDeployer.sol/DeterministicDeployer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "instance",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "bytecodeHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "factory",
        type: "string",
      },
    ],
    name: "Deployed",
    type: "event",
  },
];

export class DeterministicDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): DeterministicDeployerInterface {
    return new utils.Interface(_abi) as DeterministicDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DeterministicDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DeterministicDeployer;
  }
}
