/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721TokenReceiverUpgradeable__factory } from "./ERC721TokenReceiverUpgradeable__factory";
export { ERC721Upgradeable__factory } from "./ERC721Upgradeable__factory";
