/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721Sol from "./ERC721.sol";
export type { erc721Sol };
import type * as extensions from "./extensions";
export type { extensions };
export type { IERC721 } from "./IERC721";
