/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TransferableUpgradeable,
  TransferableUpgradeableInterface,
} from "../../../../oz-custom/contracts/internal-upgradeable/TransferableUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "version",
        type: "uint256",
      },
    ],
    name: "Initialized",
    type: "event",
  },
];

export class TransferableUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): TransferableUpgradeableInterface {
    return new utils.Interface(_abi) as TransferableUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TransferableUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TransferableUpgradeable;
  }
}
