/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721UpgradeableSol from "./ERC721Upgradeable.sol";
export type { erc721UpgradeableSol };
import type * as extensions from "./extensions";
export type { extensions };
export type { IERC721Upgradeable } from "./IERC721Upgradeable";
