/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMultichainDeployer,
  IMultichainDeployerInterface,
} from "../../../contracts/interfaces/IMultichainDeployer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "salt_",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "bytecode_",
        type: "bytes",
      },
    ],
    name: "deploy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMultichainDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IMultichainDeployerInterface {
    return new utils.Interface(_abi) as IMultichainDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMultichainDeployer {
    return new Contract(address, _abi, signerOrProvider) as IMultichainDeployer;
  }
}
