/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface Create2DeployerInterface extends utils.Interface {
  functions: {
    "instanceOf(bytes32,bytes32)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "instanceOf"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "instanceOf",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "instanceOf", data: BytesLike): Result;

  events: {
    "Deployed(address,bytes32,bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deployed"): EventFragment;
}

export interface DeployedEventObject {
  instance: string;
  salt: string;
  bytecodeHash: string;
  factory: string;
}
export type DeployedEvent = TypedEvent<
  [string, string, string, string],
  DeployedEventObject
>;

export type DeployedEventFilter = TypedEventFilter<DeployedEvent>;

export interface Create2Deployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Create2DeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    instanceOf(
      salt_: PromiseOrValue<BytesLike>,
      bytecodeHash_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { instance: string; isDeployed: boolean }>;
  };

  instanceOf(
    salt_: PromiseOrValue<BytesLike>,
    bytecodeHash_: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[string, boolean] & { instance: string; isDeployed: boolean }>;

  callStatic: {
    instanceOf(
      salt_: PromiseOrValue<BytesLike>,
      bytecodeHash_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { instance: string; isDeployed: boolean }>;
  };

  filters: {
    "Deployed(address,bytes32,bytes32,string)"(
      instance?: PromiseOrValue<string> | null,
      salt?: PromiseOrValue<BytesLike> | null,
      bytecodeHash?: PromiseOrValue<BytesLike> | null,
      factory?: null
    ): DeployedEventFilter;
    Deployed(
      instance?: PromiseOrValue<string> | null,
      salt?: PromiseOrValue<BytesLike> | null,
      bytecodeHash?: PromiseOrValue<BytesLike> | null,
      factory?: null
    ): DeployedEventFilter;
  };

  estimateGas: {
    instanceOf(
      salt_: PromiseOrValue<BytesLike>,
      bytecodeHash_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    instanceOf(
      salt_: PromiseOrValue<BytesLike>,
      bytecodeHash_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
